### ISSUE TITLE
what license?

### ISSUE THREAD

**Issue by ryw** [kelvich/pg_tiktoken#1]

**Comment by vrmiguel** [comment]
Hey @kelvich, great work on this lib :tada: 

We are interested in incorporating `pg_tiktoken` into the open-source Postgres extensions manager/registry, [Trunk](https://pgt.dev/).

In order to proceed with this integration, however, we kindly request the project to be licensed under an OSI-approved license. Would you be open to considering this requirement?

**Comment by kelvich** [comment]
Oh, sorry. I somehow missed notifications for that thread. I guess Apache should work for you?

**Comment by kelvich** [comment]
done in https://github.com/kelvich/pg_tiktoken/commit/d10b6638a85e964d3b425df35396bd4dc41c8f1c
